/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveMd: typeof import('./.vitepress/theme/components/archive-md.vue')['default']
    BackToTop: typeof import('./.vitepress/theme/components/back-to-top.vue')['default']
    Breadcrumb: typeof import('./.vitepress/theme/components/breadcrumb.vue')['default']
    CopyRight: typeof import('./.vitepress/theme/components/copy-right.vue')['default']
    DemoContainer: typeof import('./.vitepress/theme/components/demo-container.vue')['default']
    DemoTest: typeof import('./.vitepress/theme/components/demo-test.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    Heatmap: typeof import('./.vitepress/theme/components/heatmap.vue')['default']
    PageInfo: typeof import('./.vitepress/theme/components/page-info.vue')['default']
    Tag: typeof import('./.vitepress/theme/components/tag.vue')['default']
    WordCloud: typeof import('./.vitepress/theme/components/word-cloud.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
